### PR TITLE
added oddeven program in challenge

### PR DESCRIPTION
**Pull request by AnonymousSudh**
challenge accepted for oddeven program

### CODE REVIEW

**Review by HarshitRV — CHANGES_REQUESTED** [review]
Delte all comments and restructure your code.

**Comment by AnonymousSudh** [comment]
@HarshitRV  done

**Comment by HarshitRV** [comment]
LGTM👍

**Comment by Hritvik-Mohan** [comment]
Thanks for your contribution. 🎉

**Pull request merged**
